POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email":"testsauce5@gmail.com",
    "password":"vM8oA1eH0xW5dD5a@"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"testsauce10@gmail.com",
    "password":"tE8cK4gH7bB3jX3j@"
}
###
GET http://localhost:3000/api/sauces/606d99b5b1ed9f218d702e78
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZkODI2ZjNiZDYyMDIyMDkwMDAzYWQiLCJpYXQiOjE2MTc3OTY0OTIsImV4cCI6MTYxNzg4Mjg5Mn0.p8sqiNXZXkUzvov8nbx6t-PPVsjw7zByjt6vGX7K3sE
###

PUT http://localhost:3000/api/sauces/606d99b5b1ed9f218d702e78
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZkODI2ZjNiZDYyMDIyMDkwMDAzYWQiLCJpYXQiOjE2MTc3OTY0OTIsImV4cCI6MTYxNzg4Mjg5Mn0.p8sqiNXZXkUzvov8nbx6t-PPVsjw7zByjt6vGX7K3sE
Content-Type: application/json

{
    "manufacturer": "testyy",
    "userId": "606d826f3bd62022090003ad"
}
###






