POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email":"testsauce5@gmail.com",
    "password":"vM8oA1eH0xW5dD5a@"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"testsauce6@gmail.com",
    "password":"lF4wC8sL1jK9sA0d@"
}
###
GET http://localhost:3000/api/sauces/605a651f0c3cdaf244fe9ab9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDVhNjU1YjBjM2NkYWYyNDRmZTlhYmEiLCJpYXQiOjE2MTY1Mzc0MzAsImV4cCI6MTYxNjYyMzgzMH0.5BMoFfgO0Zk53AMv2Iu9KVMEzHQZLg-kLY1MUwR_hVI
###

PUT http://localhost:3000/api/sauces/606d82903bd62022090003ae
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZkODJiODNiZDYyMDIyMDkwMDAzYWYiLCJpYXQiOjE2MTc3OTIyMDIsImV4cCI6MTYxNzg3ODYwMn0.OAbAHznSk6MCsGFNpg_GDoHey9T2jBtLTPmNvqMqUr4
Content-Type: application/json

{
    "manufacturer": "testy",
    "userId": "606d82b83bd62022090003af"
}
###






